### ISSUE TITLE
Automatize data setting up and pm2 processes

### ISSUE THREAD

**Issue by pemaxim** [boxmls/service-mls-api#4]
## Objectives

On starting `service-mls-api` all MLS data should be indexed automatically and pm2 processes should be started as well.

## Tasks

* [x] Be sure that AWS S3 is accessible and images are being uploaded successfully
* [x] Be sure that RETS API is accessible and expected responses are being returned (`service-rets-api` service must be started as well).
* [x] pm2 processes (`ecosystem.config.js`)  must be started automatically on starting the container.
* [x] `grunt setup-elastic-mapping` ( setup ES index mapping ) must be executed on starting the container
* [x] `grunt index` must be executed on starting the container
* [x] `grunt get-field-schema` must be executed on starting the container.

**Comment by fqjony** [comment]
@pemaxim done. Closing the issue.
